languageCode = "en-US"
languageName = "English (U.S.)"
languageDirection = "ltr"
weight = 1

title = "chxp.dev"
copyright = "&copy; 2025 Gokul Swami"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["projects"]
  description = "Gokul's website and project portfolio"

[params.author]
  name = "Gokul Swami"
  image = "img/meems.jpg"
  headline = "Electrical Engineering Graduate Student"
  bio = "MSEE student studying VLSI"
  links = [
    { mastodon = "https://mastodon.social/@chxpdev" },
    { bluesky = "https://bsky.app/profile/chxp.dev" },
  ]
