baseURL: "https://site.gokulswam.me/"
languageCode: en-us
title: "Gokul Swami's site"
theme: dead-simple
menu:
  main:
    - name: "<u>H</u>ome"
      url: /
      weight: 1
    - name: "<u>A</u>bout"
      url: "/about"
      weight: 3
    - name: "<u>P</u>osts"
      url: "/posts"
      weight: 3

params:
  author:
    name: Gokul Swami

  description: "Gokul Swami's site"
  noSearch: true

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

services:
  rss:
    limit: -1

module:
  imports:
    - path: github.com/hugomods/images